# Generated by Django 4.0.6 on 2022-07-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMessageMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textsend', models.CharField(blank=True, max_length=100, null=True, verbose_name='Содержание')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото-файл')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщение',
                'ordering': ['id'],
            },
        ),
    ]
