# Generated by Django 4.0.6 on 2022-07-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmessage', '0002_delete_photofilemode_messagemode_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemode',
            old_name='file',
            new_name='file_this',
        ),
    ]
