# Generated by Django 4.0.6 on 2022-07-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmessage', '0003_rename_file_messagemode_file_this'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFileMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_file', models.FileField(upload_to='', verbose_name='Фото-файл')),
            ],
            options={
                'verbose_name': 'Фото-файл',
                'verbose_name_plural': 'Фото-файл',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='messagemode',
            name='file_this',
        ),
    ]
