# Generated by Django 4.0.6 on 2022-07-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmessage', '0006_alter_photofilemode_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoFileMode',
        ),
        migrations.AlterModelOptions(
            name='messagemode',
            options={'ordering': ['id'], 'verbose_name': 'Сообщение-Файл', 'verbose_name_plural': 'Сообщение-Файл'},
        ),
        migrations.AddField(
            model_name='messagemode',
            name='docfile',
            field=models.FileField(default=1, upload_to='', verbose_name='Фото-файл'),
            preserve_default=False,
        ),
    ]
