# Generated by Django 4.0.6 on 2022-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmessage', '0009_remove_photofilemode_file_photofilemode_docfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoFileMode',
        ),
        migrations.AddField(
            model_name='messagemode',
            name='docfile',
            field=models.FileField(default=1, upload_to='', verbose_name='Фото-файл'),
            preserve_default=False,
        ),
    ]
