# Generated by Django 4.0.6 on 2022-07-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Фото-файл')),
            ],
            options={
                'verbose_name': 'Фото-файл',
                'verbose_name_plural': 'Фото-файл',
            },
        ),
        migrations.AlterField(
            model_name='buttonmode',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
