# Generated by Django 4.0.6 on 2022-07-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0002_photofile_alter_buttonmode_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Совет',
                'verbose_name_plural': 'Совет',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='photofile',
            options={'ordering': ['id'], 'verbose_name': 'Фото-файл', 'verbose_name_plural': 'Фото-файл'},
        ),
        migrations.AlterField(
            model_name='photofile',
            name='file',
            field=models.FileField(upload_to='media', verbose_name='Фото-файл'),
        ),
    ]
