# Generated by Django 4.0.6 on 2022-07-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0003_advicemode_alter_photofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Подсказка',
                'verbose_name_plural': 'Подсказка',
                'ordering': ['id'],
            },
        ),
    ]
