# Generated by Django 4.0.6 on 2022-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0004_ticketmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmode',
            name='navzone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Содержание'),
        ),
    ]
