# Generated by Django 4.0.6 on 2022-07-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0005_ticketmode_navzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmode',
            name='includezone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка'),
        ),
    ]
