# Generated by Django 4.0.6 on 2022-07-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTableMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организация',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoleTableMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роль',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserTableMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия')),
                ('mainname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionTableMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcontainer.organizationtablemode', verbose_name='Организация')),
                ('roles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcontainer.roletablemode', verbose_name='Роль')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcontainer.usertablemode', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Организация-Роль-Пользователь',
                'verbose_name_plural': 'Организация-Роль-Пользователь',
                'ordering': ['id'],
            },
        ),
    ]
