# Generated by Django 4.0.6 on 2022-07-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcontainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtablemode',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название организации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roletablemode',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название роли'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertablemode',
            name='firstname',
            field=models.CharField(default=1, max_length=25, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertablemode',
            name='mainname',
            field=models.CharField(default=1, max_length=20, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
